### ISSUE TITLE
Current state of the spec?

### ISSUE THREAD

**Issue by stv0g** [sunrise-choir/spec#2]
The [README](https://github.com/sunrise-choir/spec/blob/master/README.md) file of this repo confuses me:

> This repo contains a spec for secure scuttlebutt, written as an mdBook. Unlike the protocol guide, this is not to be a linear read to quickly get something working. Rather it aims to be a comprehensive reference of how scuttlebutt works.

Is the sunrise-choir spec describing the current version of SSB. It seems largely incompatible with the protocol guide? Will sunrise-choir be backward-compatible with the current version of SSB?

**Comment by AljoschaMeyer** [comment]
Everything labeled as "legacy" is what ssb currently uses. Everything else is wistful thinking. Should the wistful thinking become reality some day, it'll be in a backwards-compatible manner.

**Comment by stv0g** [comment]
Thanks for the clarification.
